### ISSUE TITLE
How to Download into ArcGIS? 

### ISSUE THREAD

**Issue by AyshaCohen** [CityofSantaMonica/GIS#10]
How can I download these files into ArcGiS? As and Shape File or something that can become a Shape File? Thank you!

**Comment by justinmank** [comment]
You can use the freeware QGIS to open GeoJSON files and Save As Shp.

**Comment by thekaveman** [comment]
[QGIS information](http://www2.qgis.org/en/site/)

**Comment by AyshaCohen** [comment]
Thanks I will try that out - However, I cannot find where to download the
file displayed. Here is a screenshot - Thanks!:

[image: Inline image 1]

Best Regards,
Aysha Rüya Cohen
UCLA Institute of Transportation Studies Scholar
Olive Tree Initiative: Armenia-Turkey, founding member
Connect with me: www.Linkedin.com/in/AyshaRuyaCohen
Cell: (805) 765-7119
