### ISSUE TITLE
No Download Link Appears

### ISSUE THREAD

**Issue by AyshaCohen** [CityofSantaMonica/GIS#11]
![image](https://cloud.githubusercontent.com/assets/10936432/6136462/aed8d022-b125-11e4-8d9a-55d3831b10d4.png)

 I cannot find where to download the file displayed. Here is a screenshot - Thanks! -Aysha

**Comment by thekaveman** [comment]
Hi Aysha,

In your screenshot above, there is a toolbar just above the map. Towards the right side of this toolbar is a button that says **Raw**.

Clicking this button opens the raw dataset (in your example, a `geojson` file). Most browsers will open the file directly in the browser - from there you can right-click and choose "Save as..." to save the file locally. Some browsers will instead prompt you to download the file upon clicking **Raw**.

**Comment by AyshaCohen** [comment]
Tried that but I just get a lot of code and can only save it in a text format, which ArcGIS cannot read. Could you please send the file to me via email (aysha@ucla.edu)? The rest of the files I can try to find elsewhere. Thanks! 

![image](https://cloud.githubusercontent.com/assets/10936432/6137223/fccdad06-b12b-11e4-8ed3-a4206aeac2a5.png)

**Comment by thekaveman** [comment]
That is correct. `geojson` is a standard, open (as in, non-proprietary) data format for geospatial data. 

ArcGIS reads shapefiles, which is a proprietary ESRI format. 

In the interest of open source and open data, most data we make available here is in the `geojson` format. The tool ([QGIS](http://www2.qgis.org/en/site/)) that we mentioned in your previous question #10 is a free tool that can convert `geojson` files into ESRI shapefile format, if that is what you need.
