### ISSUE TITLE
Shapefile Request

### ISSUE THREAD

**Issue by cartomeo** [CityofSantaMonica/GIS#12]
Hi there. Writing to see how shapefiles of certain datasets can be obtained? Currently unable to work with GeoJSON. Interested in the following: Zoning, Tsunami Zone, Historic Landmarks & Districts, City Boundary (though can use kml if need be). Thanks!

**Comment by zrobby** [comment]
Hello, I'd be happy to provide you with that data. Please send an email to zach.robinson@smgov.net to complete this request.
