### ISSUE TITLE
Shapefile Parking Regulation

### ISSUE THREAD

**Issue by hamzaouazzani** [CityofSantaMonica/GIS#15]
Hi, 

I would love to get the Shapefiles for the parking regulations (Residential parking, meters, street cleaning and tow_away).

It would be awesome if the data in the shapefile was sorted street segment by street segment.

Thanks

**Comment by justinmank** [comment]
Preferential parking, meters and street sweeping are here as geojson: 
http://github.com/CityofSantaMonica/GIS/tree/master/streets
Geojson can be converted to shapefile easily w/QGIS. 
We don't have tow away data yet, but hope to at some point.

**Comment by hamzaouazzani** [comment]
Thank you for your answer. Really appreciate it.
We hope to launch Spot Angels in Santa Monica before the end of the month.
It's an app that helps drivers understand and respect the parking
regulations.
Would be great if you can help us promote it in Santa Monica.
Hamza
