### ISSUE TITLE
Airport GIS layer?

### ISSUE THREAD

**Issue by DRP-GIS-DHoffman** [CityofSantaMonica/GIS#16]
Hello,

I work for Los Angeles County Department of Regional Planning, and we are working on updating a countywide Airport Runways / Taxiways layer.  I'm curious if the city of Santa Monica has this as a GIS layer that it would be willing to share?

Thanks much!
Dan Hoffman, GISP

**Comment by thekaveman** [comment]
@justinmank will upload the runway shapefile into the new `/transportation` directory, as soon as #17 is done.
