### ISSUE TITLE
Parking meter information/public parking

### ISSUE THREAD

**Issue by m84lanz** [CityofSantaMonica/GIS#18]
I am looking for a shapefile of data containing information on parking meters and public parking lots in Santa Monica California.

**Comment by thekaveman** [comment]
@m84lanz have you checked out our [Parking API site](https://parking.api.smgov.net/)? We have endpoints for the [lot](https://parking.api.smgov.net/lots) and [meter](https://parking.api.smgov.net/meters) information, among others. 

Let us know if you're looking for something more and/or different.

**Comment by m84lanz** [comment]
Great, thank you so much! I will check it out.

**Comment by thekaveman** [comment]
@m84lanz did the Parking API site provide you with the information you were looking for? Can this issue be closed?

**Comment by thekaveman** [comment]
Please open a new issue here or on the [Parking API repo](https://github.com/CityofSantaMonica/Orchard.ParkingData/issues) with additional questions
